name: 'Electron Build and Release'

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build frontend static files
        run: npm run build

      - name: Build and Package Electron binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PUBLISH_OPTION="never"
          else
            PUBLISH_OPTION="always"
          fi

          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            npx electron-builder --mac --publish $PUBLISH_OPTION
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            npx electron-builder --win --publish $PUBLISH_OPTION
          else
            npx electron-builder --linux --publish $PUBLISH_OPTION
          fi
        shell: bash
